import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import { Poppins } from "next/font/google";
import Header from "../components/layouts/Header";
import FloatingButton from "../components/ui/FloatingChatButton";
import Footer from "@/components/layouts/Footer";
import { AuthProvider } from "../context/AuthContext";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "600", "700", "900"],
});

export const metadata = {
  title: "Department of Business Registration",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <AuthProvider>
          <Header />
          {children}
          <FloatingButton label="Chat" />
          <Footer />
          <Toaster
            position="top-right"
            toastOptions={{
              style: { borderRadius: '12px' },
              success: { duration: 3500 },
              error: { duration: 5000 },
            }}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
