import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  variable : "--font-poppins",
  weight: ["400", "600", "700", "900"],
});

export const metadata = {
  title: "Department of Business Registration",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.va} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
