// src/data/requests.js
export const requests = [
  {
    id: "req-1001",
    companyName: "Lanka Eco Tours",
    ownerName: "Tharushi Jayasinghe",
    businessType: "Sole Proprietor",
    businessCategory: "Travel & Tourism",
    status: "Verified",
    requestDate: "2025-07-19",
  },
  {
    id: "req-1002",
    companyName: "Blue Ocean IT Solutions",
    ownerName: "Kasun Fernando",
    businessType: "Partnership",
    businessCategory: "Software & Technology Services",
    status: "Pending",
    requestDate: "2025-07-05",
  },
  {
    id: "req-1003",
    companyName: "Lanka Eco Tours",
    ownerName: "Tharushi Jayasinghe",
    businessType: "Sole Proprietor",
    businessCategory: "Travel & Tourism",
    status: "Verified",
    requestDate: "2025-07-19",
  },
  {
    id: "req-1004",
    companyName: "Blue Ocean IT Solutions",
    ownerName: "Kasun Fernando",
    businessType: "Partnership",
    businessCategory: "Software & Technology Services",
    status: "Pending",
    requestDate: "2025-07-05",
  },
  {
    id: "req-1005",
    companyName: "Ceylon Agro Traders",
    ownerName: "Ishara Perera",
    businessType: "Private Limited",
    businessCategory: "Agriculture",
    status: "Pending",
    requestDate: "2025-07-12",
  },
  {
    id: "req-1006",
    companyName: "Serendib Crafts",
    ownerName: "Nethmi Ranasinghe",
    businessType: "Sole Proprietor",
    businessCategory: "Retail & Handicrafts",
    status: "Verified",
    requestDate: "2025-07-03",
  },
];
